meta_product_name: "Essential Critical Care"
meta_title: "Essential Critical Care"
meta_description: "This is Essential Critical Care. Resource for providing information, infographics, pdfs and videos on essential ICU training."
meta_image: "cover.jpg" # should exist in `app/assets/images/`
